name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: 0.14.1
      ZIG_URL: https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Release Tag or SHA
        id: set_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Download Zig
        run: |
          wget $ZIG_URL -O zig.tar.xz
          mkdir -p zig
          tar -xf zig.tar.xz --strip-components=1 -C zig
          echo "$(pwd)/zig" >> $GITHUB_PATH

      - name: Build with Zig
        run: |
          zig/zig build -Dpackage_release=true

      - name: Package binaries
        run: |
          cd zig-out
          for dir in *; do
            if [ -d "$dir" ]; then
              tar -czvf "$dir.tgz" -C "$dir" .
            fi
          done

      - name: Generate Changelog Since Previous Tag
        id: changelog
        run: |
          set -e
          current_tag="${GITHUB_REF#refs/tags/}"
          tags=$(git tag --sort=-creatordate)
          prev_tag=""
          found=""
          for tag in $tags; do
            if [ "$found" = "yes" ]; then
              prev_tag="$tag"
              break
            fi
            if [ "$tag" = "$current_tag" ]; then
              found="yes"
            fi
          done

          echo "## Changelog" > CHANGELOG.md
          if [ -n "$prev_tag" ]; then
            git log --pretty=format:"- %s ([%h](https://github.com/${GITHUB_REPOSITORY}/commit/%H))" "$prev_tag..$current_tag" >> CHANGELOG.md
          else
            echo "First release or previous tag not found." >> CHANGELOG.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/*.tgz
          body_path: CHANGELOG.md
          make_latest: true
          name: blackcat ${{ steps.set_tag.outputs.tag }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
